### ISSUE TITLE
credentials for requests

### ISSUE THREAD

**Issue by uyriq** [Lifailon/TorAPI#1]
запустил, дает ответ, все ок. но есть вопрос
https://github.com/Lifailon/TorAPI/blob/9727f76ccae31d02d4a59c81c1f256d35dfffce4/main.js#L260
поясните, зачем нужны куки от яндекс метрики?

**Comment by uyriq** [comment]
еще вот на кинозале есть полезная информация 
Голосование
[IMDb8.0](https://www.imdb.com/title/tt7587890/)
[Кинопоиск8.4](https://www.kinopoisk.ru/film/1142153)
Оценка 8.1 из 10
Голосов 11
это отличается от других трекеров, но ифно полезная

**Comment by Lifailon** [comment]
Спасибо за хорошее предложение, использую это в проекте [Kinozal-Bot](https://github.com/Lifailon/Kinozal-Bot), добавлю в следующем выпуске. Также добавлю поддержку Proxy и параметризацию запуска.

**Comment by Lifailon** [comment]
> поясните, зачем нужны куки от яндекс метрики?

Не сразу заметил данный вопрос, яндекс метрика не используется, cookie взяты целиком из запроса трекера и применяются для получения info hash и списка файлов, т.к. эта информация не является публичной.

**Comment by Lifailon** [comment]
> Голосование

Добавил:

```json
...
    "IMDb_Rating": "8.0",
    "Kinopoisk_Rating": "8.4",
    "Kinozal_Rating": "8.9",
    "Votes": "35",
...
```

**Comment by Lifailon** [comment]
> Также добавлю поддержку Proxy и параметризацию запуска.

Добавлено.
